# Generated by Django 4.1 on 2022-08-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.BigIntegerField()),
                ("owner_name", models.CharField(max_length=255)),
                ("thumb_url", models.URLField()),
                ("description", models.TextField()),
                ("total_score", models.IntegerField()),
                ("total_tasks", models.IntegerField()),
                ("unchangeable", models.BooleanField()),
                ("include_weekly_report", models.BooleanField()),
                (
                    "content_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Course"), (2, "Quiz"), (3, "Literature")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("draft", models.BooleanField()),
                ("icon_url", models.URLField(null=True)),
                ("small_url", models.URLField(null=True)),
                ("thumb_url", models.URLField(null=True)),
                ("icon_content_type", models.CharField(max_length=255, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
